version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_DATABASE: keitaro
      DB_USERNAME: keitaro
      DB_PASSWORD: secret
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keitaro
      MYSQL_USER: keitaro
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: